### ISSUE TITLE
Get the Redsys response in the controler

### ISSUE THREAD

**Issue by pbelmonteh** [ferotres/redsys-bundle#1]
How can I get the Redsys response in the controler, without event listeners? Is it possible?

Thank you very much for this Bundle and the documentation!!

**Comment by ferotres** [comment]
The raw assync  response of redsys is managed in the controller provided inside the bundle, this dispatch the event and build the RedsysResponse Object. Without change the behavior of the bundle is not posible receive the RedsysResponse in the controller.
