### ISSUE TITLE
The service "ferotres_redsys.controller.redsys_controller" has a dependency on a non-existent service "debug.event_dispatcher.inner".

### ISSUE THREAD

**Issue by pbelmonteh** [ferotres/redsys-bundle#3]
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                          
 The service "ferotres_redsys.controller.redsys_controller" has a dependency on a non-existent service "debug.event_dispatcher.inner".

in vendor/ferotres/redsys-bundle/src/Resources/config/services.xml:

<service
            id="ferotres_redsys.controller.redsys_controller"
            class="Ferotres\RedsysBundle\Controller\RedsysController"
            public="true"
        >
            <argument type="service" id="ferotres_redsys.redirection" />
            <argument type="service" id="debug.event_dispatcher.inner" />
            <argument type="service" id="ferotres_redsys.order_response_validator" />
        </service>

**Comment by pbelmonteh** [comment]
Fixed changing: debug.event_dispatcher.inner

by: event_dispatcher

**Comment by ferotres** [comment]
O yes, this was a mistake, thanks a lot for see this error.
